---
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: silly-demo-videos
spec:
  credentials:
    scheme: postgres
    host: silly-demo-rw.silly-demo
    port: 5432
    user: app
    passwordFrom:
      secretKeyRef:
        key: password
        name: silly-demo-app
    database: app
    parameters:
      sslmode: disable
  schema:
    sql: |
      create table videos (
        id varchar(50) not null,
        title varchar(255) not null,
        primary key (id)
      );
      create table comments (
        id serial,
        video_id varchar(50) not null,
        description text not null,
        primary key (id),
        CONSTRAINT fk_videos FOREIGN KEY(video_id) REFERENCES videos(id)
      );
